services:
  - type: web
    name: jutta-lagani-web
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.13
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jutta-lagani-db
          property: connectionString

databases:
  - name: jutta-lagani-db
    plan: free
    databaseName: jutta_lagani
    user: jutta_lagani_user

